FROM fedora:latest

WORKDIR /root

RUN dnf upgrade -y --refresh \
    && dnf install -y tree git \
    && dnf group install 'C Development Tools and Libraries' \
    && dnf autoremove -y \
    && dnf clean all \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && git clone https://github.com/mpmoran/csvsql-rs.git

WORKDIR /root/csvsql-rs
