name: Rust

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-x86_64-linux-gnu"
          path: "target/debug/csvsql"
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmarks
        run: cargo bench
      # - name: Upload benchmark results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: "csvsql-rs-x86_64-linux-gnu"
      #     path: "target/debug/csvsql"
