name: test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-gnu-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-binary-linux-gnu-x86_64"
          path: "target/debug/csvsql"
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmarks
        run: cargo bench --verbose
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-benchmarks-linux-gnu-x86_64"
          path: "target/criterion"

  build-apple-darwin-x86_64:
    needs:
      - build-linux-gnu-x86_64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-binary-apple-darwin-x86_64"
          path: "target/debug/csvsql"
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmarks
        run: cargo bench --verbose
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-benchmarks-apple-darwin-x86_64"
          path: "target/criterion"

  build-windows-msvc-x86_64:
    needs:
      - build-linux-gnu-x86_64
      - build-apple-darwin-x86_64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-binary-windows-msvc-x86_64"
          path: "target/debug/csvsql.exe"
      - name: Run tests
        run: cargo test --verbose
      - name: Run benchmarks
        run: cargo bench --verbose
      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: "csvsql-rs-benchmarks-windows-msvc-x86_64"
          path: "target/criterion"

  compute-artifact-checksums:
    needs:
      - build-linux-gnu-x86_64
      - build-apple-darwin-x86_64
      - build-windows-msvc-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: csvsql-rs-binary-linux-gnu-x86_64
          path: csvsql-rs-binary-linux-gnu-x86_64
      - name: Compute checksum for Linux binary
        run: sha256sum csvsql
        working-directory: csvsql-rs-binary-linux-gnu-x86_64
      - uses: actions/download-artifact@v2
        with:
          name: csvsql-rs-binary-apple-darwin-x86_64
          path: csvsql-rs-binary-apple-darwin-x86_64
      - name: Compute checksum for macOS binary
        run: sha256sum csvsql
        working-directory: csvsql-rs-binary-apple-darwin-x86_64
      - uses: actions/download-artifact@v2
        with:
          name: csvsql-rs-binary-windows-msvc-x86_64
          path: csvsql-rs-binary-windows-msvc-x86_64
      - name: Compute checksum for Windows binary
        run: sha256sum csvsql.exe
        working-directory: csvsql-rs-binary-windows-msvc-x86_64
